on: [push]

jobs:
  test:
      runs-on: ubuntu-latest
      name: shellcheck the shellchecker
      steps:
        - uses: actions/checkout@master
        - name: check checker
          id: check
          uses: npmaile/GH-Actions-ShellCheck@master
          with:
            find_regex: '.*\.sh'
